### ISSUE TITLE
Bug: Edit floor area errors out after creating a fresh floor

### ISSUE THREAD

**Issue by khushbuthakur** [Theo-s-Meta-Capstone/IndoorMaps#43]
After creating the floor, I went to edit floor areas option and it resulted in an error: 
https://indoormaps.onrender.com/building/8/editor
![Screenshot 2024-07-22 at 11 53 42 AM](https://github.com/user-attachments/assets/08c60cff-a96d-41e7-b7dd-31af1fc45580)

**Comment by dumax315** [comment]
Should be fixed after [hotfix: refresh both floor and area data after new floor](https://github.com/Theo-s-Meta-Capstone/IndoorMaps/commit/ddc7697872194b36448427412ebbb31a7029eb2f)
